services:
  # Spring Boot 백엔드 애플리케이션
  tdc-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tdc-app
    expose:
      - "8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DRIVER=${DB_DRIVER}
      - SPRING_JWT_SECRET=${SPRING_JWT_SECRET}
      - GMS_API_KEY=${GMS_API_KEY}
      - VITE_AMPLITUDE_API_KEY=${VITE_AMPLITUDE_API_KEY}
    restart: unless-stopped

  # Nginx 웹 서버 및 리버스 프록시
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Nginx 설정 파일
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # SSL 인증서
      - /etc/letsencrypt:/etc/letsencrypt:ro
      # 프론트엔드 빌드 파일
      - ./frontend:/usr/share/nginx/html:ro
      # 로그 파일 (디버깅용)
      - nginx_logs:/var/log/nginx
    depends_on:
      - tdc-app
    restart: unless-stopped

# 데이터 영속성을 위한 볼륨
volumes:
  nginx_logs:
    driver: local

# 기본 네트워크 (Docker가 자동으로 IP 할당)
networks:
  default:
    driver: bridge