// 에러 코드 정의
export const MIGRATION_ERROR_CODES = {
  INVALID_MIGRATION: "INVALID_MIGRATION",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  GUEST_EXPIRED: "GUEST_EXPIRED",
  NICKNAME_DUPLICATE: "NICKNAME_DUPLICATE",
} as const;

export type MigrationErrorCode =
  (typeof MIGRATION_ERROR_CODES)[keyof typeof MIGRATION_ERROR_CODES];
